# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7738e65bc3590e70f8c79fc077d6435b9673db1ac419525c972ca4f786df1c59c2be66ea62ca74ba0b1708748c8f749a5fe0a56d76d30a3fc816eb900d1db9b7

test:
  secret_key_base: 3b4a08ad65c954301a72dde475ba27fdbe84b7cd5d7294a6acbfea71a84891cd24b2df786bc2abed5f9141fbc10d48fce16680e06a9e2813a36a540af38c58c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
